name: Move already-read papers to archive

on:
  workflow_dispatch:

env:
  PAPER_LIST_ISSUE_NO: 1
  ARCHIVE_LIST_ISSUE_NO: 2

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      # Needed for posting converted files to the repo.
      issues: write

    steps:
      - name: Move already-read papers to archive
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ env.PAPER_LIST_ISSUE_NO }}
            });

            console.log(JSON.stringify(comments));


            // Filter comments that have a :+1: reaction.
            const filteredComments = comments.filter(comment => comment.reactions["+1"] > 0);
            console.log(JSON.stringify(filteredComments));

            return;
            // Move the comments to the archive list issue.
            for (const comment of filteredComments) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ env.ARCHIVE_LIST_ISSUE_NO }},
                body: comment.body
              });
              await github.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id
              });
            }